### ISSUE TITLE
Error: Incorrect or invalid username/password

### ISSUE THREAD

**Issue by Hocnonsense** [grst/rstudio-server-conda#28]
Thanks for your repository! It helps me a lot in the past two years. I'm using the `singularity` part

However, after I update R 4.1 to 4.2, the old version of `rserver` cannot draw figure in the `plots` channel anymore, and I upgraded to the latest version. I did run the singularity:
![image](https://user-images.githubusercontent.com/48747984/209672231-488e9ff7-6e1d-4a0f-800d-3719f29825ef.png)

But I cannot login in the server on explorer, I've tried many combinations: root, `whoami`, rstudio, and their passwords, none of them success.
![image](https://user-images.githubusercontent.com/48747984/209672264-dd2bbf92-1575-4619-8e72-2c70cb85a892.png)

Do you have any idea? Thanks!

**Comment by grst** [comment]
The password should always be the one you set per environment variable. The default is `notsafe`. The user name is either `rstudio` or your actual user name. It's a bit weird because on one of my systems `rstudio` works, on another one only my username works. I haven't found out yet what the reason is. 

If you upgrade rstudio server, also try clearing cache and cookies.

**Comment by Hocnonsense** [comment]
Thanks for your kind reply!

I finally went back to use my previous build singularity (2 years ago), because even after I used the "local" version of `rserver`, the error message "Incorrect or invalid username/password" still exists.
I restarted the computer, deleted the `tmp` folder, and waited for output to "syslog". None helped me.
